package g2diagnostic

// ----------------------------------------------------------------------------
// Constants
// ----------------------------------------------------------------------------

// Log message prefix.
const Prefix = "g2diagnostic."

// ----------------------------------------------------------------------------
// Variables
// ----------------------------------------------------------------------------

// Message templates for g2diagnostic implementations.
var IdMessages = map[int]string{
	1:    "Enter " + Prefix + "CheckDBPerf(%d).",
	2:    "Exit  " + Prefix + "CheckDBPerf(%d) returned (%s, %v).",
	3:    "Enter " + Prefix + "ClearLastException().",
	4:    "Exit  " + Prefix + "ClearLastException() returned (%v).",
	5:    "Enter " + Prefix + "CloseEntityListBySize().",
	6:    "Exit  " + Prefix + "CloseEntityListBySize() returned (%v).",
	7:    "Enter " + Prefix + "Destroy().",
	8:    "Exit  " + Prefix + "Destroy() returned (%v).",
	9:    "Enter " + Prefix + "FetchNextEntityBySize().",
	10:   "Exit  " + Prefix + "FetchNextEntityBySize() returned (%s, %v).",
	11:   "Enter " + Prefix + "FindEntitiesByFeatureIDs(%s).",
	12:   "Exit  " + Prefix + "FindEntitiesByFeatureIDs(%s) returned (%s, %v).",
	13:   "Enter " + Prefix + "GetAvailableMemory().",
	14:   "Exit  " + Prefix + "GetAvailableMemory() returned (%d, %v).",
	15:   "Enter " + Prefix + "GetDataSourceCounts().",
	16:   "Exit  " + Prefix + "GetDataSourceCounts() returned (%s, %v).",
	17:   "Enter " + Prefix + "GetDBInfo().",
	18:   "Exit  " + Prefix + "GetDBInfo()  returned (%s, %v).",
	19:   "Enter " + Prefix + "GetEntityDetails(%d, %d).",
	20:   "Exit  " + Prefix + "GetEntityDetails(%d, %d) returned (%s, %v).",
	21:   "Enter " + Prefix + "GetEntityListBySize(%d).",
	22:   "Exit  " + Prefix + "GetEntityListBySize(%d) returned (%v, %v).",
	23:   "Enter " + Prefix + "GetEntityResume(%d).",
	24:   "Exit  " + Prefix + "GetEntityResume(%d) returned (%s, %v).",
	25:   "Enter " + Prefix + "GetEntitySizeBreakdown(%d, %d).",
	26:   "Exit  " + Prefix + "GetEntitySizeBreakdown(%d, %d) returned (%s, %v).",
	27:   "Enter " + Prefix + "GetFeature(%d).",
	28:   "Exit  " + Prefix + "GetFeature(%d) returned (%s, %v).",
	29:   "Enter " + Prefix + "GetGenericFeatures(%s, %d).",
	30:   "Exit  " + Prefix + "GetGenericFeatures(%s, %d) returned (%s, %v).",
	31:   "Enter " + Prefix + "GetLastException().",
	32:   "Exit  " + Prefix + "GetLastException() returned (%s, %v).",
	33:   "Enter " + Prefix + "GetLastExceptionCode().",
	34:   "Exit  " + Prefix + "GetLastExceptionCode() returned (%d, %v).",
	35:   "Enter " + Prefix + "GetLogicalCores().",
	36:   "Exit  " + Prefix + "GetLogicalCores() returned (%d, %v).",
	37:   "Enter " + Prefix + "GetMappingStatistics(%d).",
	38:   "Exit  " + Prefix + "GetMappingStatistics(%d) returned (%s, %v).",
	39:   "Enter " + Prefix + "GetPhysicalCores().",
	40:   "Exit  " + Prefix + "GetPhysicalCores() returned (%d, %v).",
	41:   "Enter " + Prefix + "GetRelationshipDetails(%d, %d).",
	42:   "Exit  " + Prefix + "GetRelationshipDetails(%d, %d) returned (%s, %v).",
	43:   "Enter " + Prefix + "GetResolutionStatistics().",
	44:   "Exit  " + Prefix + "GetResolutionStatistics() returned (%s, %v).",
	45:   "Enter " + Prefix + "GetTotalSystemMemory().",
	46:   "Exit  " + Prefix + "GetTotalSystemMemory() returned (%d, %v).",
	47:   "Enter " + Prefix + "Init(%s, %s, %d).",
	48:   "Exit  " + Prefix + "Init(%s, %s, %d) returned (%v).",
	49:   "Enter " + Prefix + "InitWithConfigID(%s, %s, %d, %d).",
	50:   "Exit  " + Prefix + "InitWithConfigID(%s, %s, %d, %d) returned (%v).",
	51:   "Enter " + Prefix + "Reinit(%d).",
	52:   "Exit  " + Prefix + "Reinit(%d) returned (%v).",
	53:   "Enter " + Prefix + "SetLogLevel(%v).",
	54:   "Exit  " + Prefix + "SetLogLevel(%v) returned (%v).",
	55:   "Enter " + Prefix + "RegisterObserver(%s).",
	56:   "Exit  " + Prefix + "RegisterObserver(%s) returned (%v).",
	57:   "Enter " + Prefix + "UnregisterObserver(%s).",
	58:   "Exit  " + Prefix + "UnregisterObserver(%s) returned (%v).",
	59:   "Enter " + Prefix + "GetSdkId().",
	60:   "Exit  " + Prefix + "GetSdkId() returned (%s).",
	4001: Prefix + "G2Diagnostic_checkDBPerf(%d) failed. Return code: %d",
	4002: Prefix + "G2Diagnostic_closeEntityListBySize() failed. Return code: %d",
	4003: Prefix + "G2Diagnostic_destroy() failed.  Return code: %d",
	4004: Prefix + "G2Diagnostic_fetchNextEntityBySize() failed.  Return code: %d",
	4005: Prefix + "G2Diagnostic_findEntitiesByFeatureIDs(%s) failed. Return code: %d",
	4006: Prefix + "G2Diagnostic_getDataSourceCounts() failed. Return code: %d",
	4007: Prefix + "G2Diagnostic_getDBInfo() failed. Return code: %d",
	4008: Prefix + "G2Diagnostic_getEntityDetails(%d, %d) failed. Return code: %d",
	4009: Prefix + "G2Diagnostic_getEntityListBySize(%d) failed. Return code: %d",
	4010: Prefix + "G2Diagnostic_getEntityResume(%d) failed. Return code: %d",
	4011: Prefix + "G2Diagnostic_getEntitySizeBreakdown(%d, %d) failed. Return code: %d",
	4012: Prefix + "G2Diagnostic_getFeature(%d) failed. Return code: %d",
	4013: Prefix + "G2Diagnostic_getGenericFeatures(%s, %d) failed. Return code: %d",
	4014: Prefix + "G2Diagnostic_getLastException() failed. Return code: %d",
	4015: Prefix + "G2Diagnostic_getMappingStatistics(%d) failed. Return code: %d",
	4016: Prefix + "G2Diagnostic_getRelationshipDetails(%d, %d) failed. Return code: %d",
	4017: Prefix + "G2Diagnostic_getResolutionStatistics() failed. Return code: %d",
	4018: Prefix + "G2Diagnostic_init(%s, %s, %d) failed. Return code: %d",
	4019: Prefix + "G2Diagnostic_initWithConfigID(%s, %s, %d, %d) failed. Return code: %d",
	4020: Prefix + "G2Diagnostic_reinit(%d) failed. Return Code: %d",
	5901: "During test setup, call to messagelogger.NewSenzingApiLogger() failed.",
	5902: "During test setup, call to g2eg2engineconfigurationjson.BuildSimpleSystemConfigurationJsonViaMap() failed.",
	5903: "During test setup, call to g2engine.Init() failed.",
	5904: "During test setup, call to g2engine.PurgeRepository() failed.",
	5905: "During test setup, call to g2engine.Destroy() failed.",
	5906: "During test setup, call to g2config.Init() failed.",
	5907: "During test setup, call to g2config.Create() failed.",
	5908: "During test setup, call to g2config.AddDataSource() failed.",
	5909: "During test setup, call to g2config.Save() failed.",
	5910: "During test setup, call to g2config.Close() failed.",
	5911: "During test setup, call to g2config.Destroy() failed.",
	5912: "During test setup, call to g2configmgr.Init() failed.",
	5913: "During test setup, call to g2configmgr.AddConfig() failed.",
	5914: "During test setup, call to g2configmgr.SetDefaultConfigID() failed.",
	5915: "During test setup, call to g2configmgr.Destroy() failed.",
	5916: "During test setup, call to g2engine.Init() failed.",
	5917: "During test setup, call to g2engine.AddRecord() failed.",
	5918: "During test setup, call to g2engine.Destroy() failed.",
	5920: "During test setup, call to setupSenzingConfig() failed.",
	5921: "During test setup, call to setupPurgeRepository() failed.",
	5922: "During test setup, call to setupAddRecords() failed.",
	5931: "During test setup, call to g2engine.Init() failed.",
	5932: "During test setup, call to g2engine.PurgeRepository() failed.",
	5933: "During test setup, call to g2engine.Destroy() failed.",
	8001: Prefix + "CheckDBPerf",
	8002: Prefix + "CloseEntityListBySize",
	8003: Prefix + "Destroy",
	8004: Prefix + "FetchNextEntityBySize",
	8005: Prefix + "FindEntitiesByFeatureIDs",
	8006: Prefix + "GetAvailableMemory",
	8007: Prefix + "GetDataSourceCounts",
	8008: Prefix + "GetDBInfo",
	8009: Prefix + "GetEntityDetails",
	8010: Prefix + "GetEntityListBySize",
	8011: Prefix + "GetEntityResume",
	8012: Prefix + "GetEntitySizeBreakdown",
	8013: Prefix + "GetFeature",
	8014: Prefix + "GetGenericFeatures",
	8015: Prefix + "GetLogicalCores",
	8016: Prefix + "GetMappingStatistics",
	8017: Prefix + "GetPhysicalCores",
	8018: Prefix + "GetRelationshipDetails",
	8019: Prefix + "GetResolutionStatistics",
	8020: Prefix + "GetTotalSystemMemory",
	8021: Prefix + "Init",
	8022: Prefix + "InitWithConfigID",
	8023: Prefix + "Reinit",
	8024: Prefix + "GetSdkId",
	8025: Prefix + "RegisterObserver",
	8026: Prefix + "SetLogLevel",
	8027: Prefix + "UnregisterObserver",
}

// Status strings for specific g2diagnostic messages.
var IdStatuses = map[int]string{}
