package g2engine

// ----------------------------------------------------------------------------
// Constants
// ----------------------------------------------------------------------------

// Log message prefix.
const Prefix = "g2engine."

// ----------------------------------------------------------------------------
// Variables
// ----------------------------------------------------------------------------

// Message templates for g2engine implementations.
var IdMessages = map[int]string{
	1:    "Enter " + Prefix + "AddRecord(%s, %s, %s, %s).",
	2:    "Exit  " + Prefix + "AddRecord(%s, %s, %s, %s) returned (%v).",
	3:    "Enter " + Prefix + "AddRecordWithInfo(%s, %s, %s, %s, %d).",
	4:    "Exit  " + Prefix + "AddRecordWithInfo(%s, %s, %s, %s, %d) returned (%s, %v).",
	11:   "Enter " + Prefix + "ClearLastException().",
	12:   "Exit  " + Prefix + "ClearLastException() returned (%v).",
	13:   "Enter " + Prefix + "CloseExport(%v).",
	14:   "Exit  " + Prefix + "CloseExport(%v) returned (%v).",
	15:   "Enter " + Prefix + "CountRedoRecords().",
	16:   "Exit  " + Prefix + "CountRedoRecords() returned (%d, %v).",
	17:   "Enter " + Prefix + "DeleteRecord(%s, %s, %s).",
	18:   "Exit  " + Prefix + "DeleteRecord(%s, %s, %s) returned (%v).",
	19:   "Enter " + Prefix + "DeleteRecordWithInfo(%s, %s, %s, %d).",
	20:   "Exit  " + Prefix + "DeleteRecordWithInfo(%s, %s, %s, %d) returned (%s, %v).",
	21:   "Enter " + Prefix + "Destroy().",
	22:   "Exit  " + Prefix + "Destroy() returned (%v).",
	23:   "Enter " + Prefix + "ExportConfigAndConfigID().",
	24:   "Exit  " + Prefix + "ExportConfigAndConfigID() returned (%s, %d, %v).",
	25:   "Enter " + Prefix + "ExportConfig().",
	26:   "Exit  " + Prefix + "ExportConfig() returned (%s, %v).",
	27:   "Enter " + Prefix + "ExportCSVEntityReport(%s, %d).",
	28:   "Exit  " + Prefix + "ExportCSVEntityReport(%s, %d) returned (%v, %v).",
	29:   "Enter " + Prefix + "ExportJSONEntityReport(%d).",
	30:   "Exit  " + Prefix + "ExportJSONEntityReport(%d) returned (%v, %v).",
	31:   "Enter " + Prefix + "FetchNext(%v).",
	32:   "Exit  " + Prefix + "FetchNext(%v) returned (%s, %v).",
	33:   "Enter " + Prefix + "FindInterestingEntitiesByEntityID(%d, %d).",
	34:   "Exit  " + Prefix + "FindInterestingEntitiesByEntityID(%d, %d) returned (%s, %v).",
	35:   "Enter " + Prefix + "FindInterestingEntitiesByRecordID(%s, %s, %d).",
	36:   "Exit  " + Prefix + "FindInterestingEntitiesByRecordID(%s, %s, %d) returned (%s, %v).",
	37:   "Enter " + Prefix + "FindNetworkByEntityID(%s, %d, %d, %d).",
	38:   "Exit  " + Prefix + "FindNetworkByEntityID(%s, %d, %d, %d) returned (%s, %v).",
	39:   "Enter " + Prefix + "FindNetworkByEntityID_V2(%s, %d, %d, %d, %d).",
	40:   "Exit  " + Prefix + "FindNetworkByEntityID_V2(%s, %d, %d, %d, %d) returned (%s, %v).",
	41:   "Enter " + Prefix + "FindNetworkByRecordID(%s, %d, %d, %d).",
	42:   "Exit  " + Prefix + "FindNetworkByRecordID(%s, %d, %d, %d) returned (%s, %v).",
	43:   "Enter " + Prefix + "FindNetworkByRecordID_V2(%s, %d, %d, %d, %d).",
	44:   "Exit  " + Prefix + "FindNetworkByRecordID_V2(%s, %d, %d, %d, %d) returned (%s, %v).",
	45:   "Enter " + Prefix + "FindPathByEntityID(%d, %d, %d).",
	46:   "Exit  " + Prefix + "FindPathByEntityID(%d, %d, %d) returned (%s, %v).",
	47:   "Enter " + Prefix + "FindPathByEntityID_V2(%d, %d, %d, %d).",
	48:   "Exit  " + Prefix + "FindPathByEntityID_V2(%d, %d, %d, %d) returned (%s, %v).",
	49:   "Enter " + Prefix + "FindPathByRecordID(%s, %s, %s, %s, %d).",
	50:   "Exit  " + Prefix + "FindPathByRecordID(%s, %s, %s, %s, %d) returned (%s, %v).",
	51:   "Enter " + Prefix + "FindPathByRecordID_V2(%s, %s, %s, %s, %d, %d).",
	52:   "Exit  " + Prefix + "FindPathByRecordID_V2(%s, %s, %s, %s, %d, %d) returned (%s, %v).",
	53:   "Enter " + Prefix + "FindPathExcludingByEntityID(%d, %d, %d, %s).",
	54:   "Exit  " + Prefix + "FindPathExcludingByEntityID(%d, %d, %d, %s) returned (%s, %v).",
	55:   "Enter " + Prefix + "FindPathExcludingByEntityID_V2(%d, %d, %d, %s, %d).",
	56:   "Exit  " + Prefix + "FindPathExcludingByEntityID_V2(%d, %d, %d, %s, %d) returned (%s, %v).",
	57:   "Enter " + Prefix + "FindPathExcludingByRecordID(%s, %s, %s, %s, %d, %s).",
	58:   "Exit  " + Prefix + "FindPathExcludingByRecordID(%s, %s, %s, %s, %d, %s) returned (%s, %v).",
	59:   "Enter " + Prefix + "FindPathExcludingByRecordID_V2(%s, %s, %s, %s, %d, %s, %d).",
	60:   "Exit  " + Prefix + "FindPathExcludingByRecordID_V2(%s, %s, %s, %s, %d, %s, %d) returned (%v).",
	61:   "Enter " + Prefix + "FindPathIncludingSourceByEntityID(%d, %d, %d, %s, %s).",
	62:   "Exit  " + Prefix + "FindPathIncludingSourceByEntityID(%d, %d, %d, %s, %s) returned (%s, %v).",
	63:   "Enter " + Prefix + "FindPathIncludingSourceByEntityID_V2(%d, %d, %d, %s, %s, %d).",
	64:   "Exit  " + Prefix + "FindPathIncludingSourceByEntityID_V2(%d, %d, %d, %s, %s, %d) returned (%s, %v).",
	65:   "Enter " + Prefix + "FindPathIncludingSourceByRecordID(%s, %s, %s, %s, %d, %s, %s).",
	66:   "Exit  " + Prefix + "FindPathIncludingSourceByRecordID(%s, %s, %s, %s, %d, %s, %s) returned (%s, %v).",
	67:   "Enter " + Prefix + "FindPathIncludingSourceByRecordID_V2(%s, %s, %s, %s, %d, %s, %s, %d).",
	68:   "Exit  " + Prefix + "FindPathIncludingSourceByRecordID_V2(%s, %s, %s, %s, %d, %s, %s, %d) returned (%s, %v).",
	69:   "Enter " + Prefix + "GetActiveConfigID().",
	70:   "Exit  " + Prefix + "GetActiveConfigID() returned (%d, %v).",
	71:   "Enter " + Prefix + "GetEntityByEntityID(%d).",
	72:   "Exit  " + Prefix + "GetEntityByEntityID(%d) returned (%s, %v).",
	73:   "Enter " + Prefix + "GetEntityByEntityID_V2(%d, %d).",
	74:   "Exit  " + Prefix + "GetEntityByEntityID_V2(%d, %d) returned (%s, %v).",
	75:   "Enter " + Prefix + "GetEntityByRecordID(%s, %s).",
	76:   "Exit  " + Prefix + "GetEntityByRecordID(%s, %s) returned (%s, %v).",
	77:   "Enter " + Prefix + "GetEntityByRecordID_V2(%s, %s, %d).",
	78:   "Exit  " + Prefix + "GetEntityByRecordID_V2(%s, %s, %d) returned (%s, %v).",
	79:   "Enter " + Prefix + "GetLastException().",
	80:   "Exit  " + Prefix + "GetLastException() returned (%s, %v).",
	81:   "Enter " + Prefix + "GetLastExceptionCode().",
	82:   "Exit  " + Prefix + "GetLastExceptionCode() returned (%d, %v).",
	83:   "Enter " + Prefix + "GetRecord(%s, %s).",
	84:   "Exit  " + Prefix + "GetRecord(%s, %s) returned (%s, %v).",
	85:   "Enter " + Prefix + "GetRecord_V2(%s, %s, %d).",
	86:   "Exit  " + Prefix + "GetRecord_V2(%s, %s, %d) returned (%s, %v).",
	87:   "Enter " + Prefix + "GetRedoRecord().",
	88:   "Exit  " + Prefix + "GetRedoRecord() returned (%s, %v).",
	89:   "Enter " + Prefix + "GetRepositoryLastModifiedTime().",
	90:   "Exit  " + Prefix + "GetRepositoryLastModifiedTime() returned (%d, %v).",
	91:   "Enter " + Prefix + "GetVirtualEntityByRecordID(%s).",
	92:   "Exit  " + Prefix + "GetVirtualEntityByRecordID(%s) returned (%s, %v).",
	93:   "Enter " + Prefix + "GetVirtualEntityByRecordID_V2(%s, %d).",
	94:   "Exit  " + Prefix + "GetVirtualEntityByRecordID_V2(%s, %d) returned (%s, %v).",
	95:   "Enter " + Prefix + "HowEntityByEntityID(%d).",
	96:   "Exit  " + Prefix + "HowEntityByEntityID(%d) returned (%s, %v).",
	97:   "Enter " + Prefix + "HowEntityByEntityID_V2(%d, %d).",
	98:   "Exit  " + Prefix + "HowEntityByEntityID_V2(%d, %d) returned (%s, %v).",
	99:   "Enter " + Prefix + "Init(%s, %s, %d).",
	100:  "Exit  " + Prefix + "Init(%s, %s, %d) returned (%v).",
	101:  "Enter " + Prefix + "InitWithConfigID(%s, %s, %d, %d).",
	102:  "Exit  " + Prefix + "InitWithConfigID(%s, %s, %d, %d) returned (%v).",
	103:  "Enter " + Prefix + "PrimeEngine().",
	104:  "Exit  " + Prefix + "PrimeEngine() returned (%v).",
	107:  "Enter " + Prefix + "ProcessRedoRecord().",
	108:  "Exit  " + Prefix + "ProcessRedoRecord() returned (%s, %v).",
	109:  "Enter " + Prefix + "ProcessRedoRecordWithInfo(%d).",
	110:  "Exit  " + Prefix + "ProcessRedoRecordWithInfo(%d) returned (%s, %s, %v).",
	117:  "Enter " + Prefix + "PurgeRepository().",
	118:  "Exit  " + Prefix + "PurgeRepository() returned (%v).",
	119:  "Enter " + Prefix + "ReevaluateEntity(%d, %d).",
	120:  "Exit  " + Prefix + "ReevaluateEntity(%d, %d) returned (%v).",
	121:  "Enter " + Prefix + "ReevaluateEntityWithInfo(%d, %d).",
	122:  "Exit  " + Prefix + "ReevaluateEntityWithInfo(%d, %d) returned (%s, %v).",
	123:  "Enter " + Prefix + "ReevaluateRecord(%s, %s, %d).",
	124:  "Exit  " + Prefix + "ReevaluateRecord(%s, %s, %d) returned (%v).",
	125:  "Enter " + Prefix + "ReevaluateRecordWithInfo(%s, %s, %d).",
	126:  "Exit  " + Prefix + "ReevaluateRecordWithInfo(%s, %s, %d) returned (%s, %v).",
	127:  "Enter " + Prefix + "Reinit(%d).",
	128:  "Exit  " + Prefix + "Reinit(%d) returned (%v).",
	129:  "Enter " + Prefix + "ReplaceRecord(%s, %s, %s, %s).",
	130:  "Exit  " + Prefix + "ReplaceRecord(%s, %s, %s, %s) returned (%v).",
	131:  "Enter " + Prefix + "ReplaceRecordWithInfo(%s, %s, %s, %s, %d).",
	132:  "Exit  " + Prefix + "ReplaceRecordWithInfo(%s, %s, %s, %s, %d) returned (%s, %v).",
	133:  "Enter " + Prefix + "SearchByAttributes(%s).",
	134:  "Exit  " + Prefix + "SearchByAttributes(%s) returned (%s, %v).",
	135:  "Enter " + Prefix + "SearchByAttributes_V2(%s, %d).",
	136:  "Exit  " + Prefix + "SearchByAttributes_V2(%s, %d) returned (%s, %v).",
	137:  "Enter " + Prefix + "SetLogLevel(%v).",
	138:  "Exit  " + Prefix + "SetLogLevel(%v) returned (%v).",
	139:  "Enter " + Prefix + "Stats().",
	140:  "Exit  " + Prefix + "Stats() returned (%s, %v).",
	141:  "Enter " + Prefix + "WhyEntities(%d, %d).",
	142:  "Exit  " + Prefix + "WhyEntities(%d, %d) returned (%s, %v).",
	143:  "Enter " + Prefix + "WhyEntities_V2(%d, %d, %d).",
	144:  "Exit  " + Prefix + "WhyEntities_V2(%d, %d, %d) returned (%s, %v).",
	153:  "Enter " + Prefix + "WhyRecords(%s, %s, %s, %s).",
	154:  "Exit  " + Prefix + "WhyRecords(%s, %s, %s, %s) returned (%s, %v).",
	155:  "Enter " + Prefix + "WhyRecords_V2(%s, %s, %s, %s, %d).",
	156:  "Exit  " + Prefix + "WhyRecords_V2(%s, %s, %s, %s, %d) returned (%s, %v).",
	157:  "Enter " + Prefix + "RegisterObserver(%s).",
	158:  "Exit  " + Prefix + "RegisterObserver(%s) returned (%v).",
	159:  "Enter " + Prefix + "UnregisterObserver(%s).",
	160:  "Exit  " + Prefix + "UnregisterObserver(%s) returned (%v).",
	161:  "Enter " + Prefix + "GetSdkId().",
	162:  "Exit  " + Prefix + "GetSdkId() returned (%s).",
	163:  "Enter " + Prefix + "ExportCSVEntityReportIterator(%s, %d).",
	164:  "Exit  " + Prefix + "ExportCSVEntityReportIterator(%s, %d) returned (%v, %v).",
	165:  "Enter " + Prefix + "ExportJSONEntityReportIterator(%d).",
	166:  "Exit  " + Prefix + "ExportJSONEntityReportIterator(%d) returned (%v, %v).",
	4001: Prefix + "G2_addRecord(%s, %s, %s, %s) failed. Return code: %d",
	4002: Prefix + "G2_addRecordWithInfo(%s, %s, %s, %s, %d) failed. Return code: %d",
	4006: Prefix + "G2_closeExport(%v) failed. Return code: %d",
	4007: Prefix + "G2_deleteRecord(%s, %s, %s) failed. Return code: %d",
	4008: Prefix + "G2_deleteRecordWithInfo(%s, %s, %s, %d) failed. Return code: %d",
	4009: Prefix + "G2_destroy() failed. Return code: %d",
	4010: Prefix + "G2_exportConfigAndConfigID() failed. Return code: %d",
	4011: Prefix + "G2_exportConfig() failed. Return code: %d",
	4012: Prefix + "G2_exportCSVEntityReport(%s, %d) failed. Return code: %d",
	4013: Prefix + "G2_exportJSONEntityReport(%d) failed. Return code: %d",
	4014: Prefix + "G2_fetchNext(%v) failed. Return code: %d",
	4015: Prefix + "G2_findInterestingEntitiesByEntityID(%d, %d) failed. Return code: %d",
	4016: Prefix + "G2_findInterestingEntitiesByRecordID(%s, %s, %d) failed. Return code: %d",
	4017: Prefix + "G2_findNetworkByEntityID(%s, %d, %d, %d) failed. Return code: %d",
	4018: Prefix + "G2_findNetworkByEntityID_V2(%s, %d, %d, %d, %d) failed. Return code: %d",
	4019: Prefix + "G2_findNetworkByRecordID(%s, %d, %d, %d) failed. Return code: %d",
	4020: Prefix + "G2_findNetworkByRecordID_V2(%s, %d, %d, %d, %d) failed. Return code: %d",
	4021: Prefix + "G2_findPathByEntityID(%d, %d, %d) failed. Return code: %d",
	4022: Prefix + "G2_findPathByEntityID_V2(%d, %d, %d, %d) failed. Return code: %d",
	4023: Prefix + "G2_findPathByRecordID(%s, %s, %s, %s, %d) failed. Return code: %d",
	4024: Prefix + "G2_findPathByRecordID_V2(%s, %s, %s, %s, %d, %d) failed. Return code: %d",
	4025: Prefix + "G2_findPathExcludingByEntityID(%d, %d, %d, %s) failed. Return code: %d",
	4026: Prefix + "G2_findPathExcludingByEntityID_V2(%d, %d, %d, %s, %d) failed. Return code: %d",
	4027: Prefix + "G2_findPathExcludingByRecordID(%s, %s, %s, %s %d, %s) failed. Return code: %d",
	4028: Prefix + "G2_findPathExcludingByRecordID_V2(%s, %s, %s, %s %d, %s, %d) failed. Return code: %d",
	4029: Prefix + "G2_findPathIncludingSourceByEntityID(%d, %d, %d, %s, %s) failed. Return code: %d",
	4030: Prefix + "G2_findPathIncludingSourceByEntityID_V2(%d, %d, %d, %s, %s, %d) failed. Return code: %d",
	4031: Prefix + "G2_findPathIncludingSourceByRecordID(%s, %s, %s, %s %d, %s, %s) failed. Return code: %d",
	4032: Prefix + "G2_findPathIncludingSourceByRecordID_V2(%s, %s, %s, %s %d, %s, %s, %d) failed. Return code: %d",
	4033: Prefix + "G2_getActiveConfigID() failed. Return code: %d",
	4034: Prefix + "G2_getEntityByEntityID(%d) failed. Return code: %d",
	4035: Prefix + "G2_getEntityByEntityID_V2(%d, %d) failed. Return code: %d",
	4036: Prefix + "G2_getEntityByRecordID(%s, %s) failed. Return code: %d",
	4037: Prefix + "G2_getEntityByRecordID_V2(%s, %s, %d) failed. Return code: %d",
	4038: Prefix + "G2_getLastException() failed. Return code: %d",
	4039: Prefix + "G2_getRecord(%s, %s) failed. Return code: %d",
	4040: Prefix + "G2_getRecord_V2(%s, %s, %d) failed. Return code: %d",
	4041: Prefix + "G2_getRedoRecord() failed. Return code: %d",
	4042: Prefix + "G2_getRepositoryLastModifiedTime() failed. Return code: %d",
	4043: Prefix + "G2_getVirtualEntityByRecordID(%s) failed. Return code: %d",
	4044: Prefix + "G2_getVirtualEntityByRecordID_V2(%s, %d) failed. Return code: %d",
	4045: Prefix + "G2_howEntityByEntityID(%d) failed. Return code: %d",
	4046: Prefix + "G2_howEntityByEntityID_V2(%d, %d) failed. Return code: %d",
	4047: Prefix + "G2_init(%s, %s, %d) failed. Return code: %d",
	4048: Prefix + "G2_initWithConfigID(%s, %s, %d, %d) failed. Return code: %d",
	4049: Prefix + "G2_primeEngine() failed. Return code: %d",
	4051: Prefix + "G2_processRedoRecord() failed. Return code: %d",
	4052: Prefix + "G2_processRedoRecordWithInfo(%d) failed. Return code: %d",
	4056: Prefix + "G2Diagnostic_purgeRepository() failed. Return code: %d",
	4057: Prefix + "G2_reevaluateEntity(%d, %d) failed. Return code: %d",
	4058: Prefix + "G2_reevaluateEntityWithInfo(%d, %d) failed. Return code: %d",
	4059: Prefix + "G2_reevaluateRecord(%s, %s, %d) failed. Return code: %d",
	4060: Prefix + "G2_reevaluateRecordWithInfo(%s, %s, %d) failed. Return code: %d",
	4061: Prefix + "G2_reinit(%d) failed. Return code: %d",
	4062: Prefix + "G2_replaceRecord(%s, %s, %s, %s) failed. Return code: %d",
	4063: Prefix + "G2_replaceRecordWithInfo(%s, %s, %s, %s, %d) failed. Return code: %d",
	4064: Prefix + "G2_searchByAttributes(%s) failed. Return code: %d",
	4065: Prefix + "G2_searchByAttributes_V2(%s, %d) failed. Return code: %d",
	4066: Prefix + "G2_stats() failed. Return code: %d",
	4067: Prefix + "G2_whyEntities(%d, %d) failed. Return code: %d",
	4068: Prefix + "G2_whyEntities_V2(%d, %d, %d) failed. Return code: %d",
	4073: Prefix + "G2_whyRecords(%s, %s, %s, %s) failed. Return code: %d",
	4074: Prefix + "G2_whyRecords_V2(%s, %s, %s, %s, %d) failed. Return code: %d",
	5901: "During test setup, call to messagelogger.NewSenzingApiLogger() failed.",
	5902: "During test setup, call to g2engineconfigurationjson.BuildSimpleSystemConfigurationJsonViaMap() failed.",
	5903: "During test setup, call to g2engine.Initialize() failed.",
	5904: "During test setup, call to g2diagnostic.PurgeRepository() failed.",
	5905: "During test setup, call to g2engine.Destroy() failed.",
	5906: "During test setup, call to g2config.Initialize() failed.",
	5907: "During test setup, call to g2config.Create() failed.",
	5908: "During test setup, call to g2config.AddDataSource() failed.",
	5909: "During test setup, call to g2config.GetJsonString() failed.",
	5910: "During test setup, call to g2config.Close() failed.",
	5911: "During test setup, call to g2config.Destroy() failed.",
	5912: "During test setup, call to g2configmgr.Initialize() failed.",
	5913: "During test setup, call to g2configmgr.AddConfig() failed.",
	5914: "During test setup, call to g2configmgr.SetDefaultConfigID() failed.",
	5915: "During test setup, call to g2configmgr.Destroy() failed.",
	5916: "During test setup, call to g2engine.Initialize() failed.",
	5917: "During test setup, call to g2engine.AddRecord() failed.",
	5918: "During test setup, call to g2engine.Destroy() failed.",
	5920: "During test setup, call to setupSenzingConfig() failed.",
	5921: "During test setup, call to setupPurgeRepository() failed.",
	5922: "During test setup, call to setupAddRecords() failed.",
	5931: "During test setup, call to g2engine.Initialize() failed.",
	5932: "During test setup, call to g2diagnostic.PurgeRepository() failed.",
	5933: "During test setup, call to g2engine.Destroy() failed.",
	8001: Prefix + "AddRecord",
	8002: Prefix + "AddRecordWithInfo",
	8006: Prefix + "CloseExport",
	8007: Prefix + "CountRedoRecords",
	8008: Prefix + "DeleteRecord",
	8009: Prefix + "DeleteRecordWithInfo",
	8010: Prefix + "Destroy",
	8011: Prefix + "ExportConfig",
	8012: Prefix + "ExportConfigAndConfigID",
	8013: Prefix + "ExportCSVEntityReport",
	8014: Prefix + "ExportJSONEntityReport",
	8015: Prefix + "FetchNext",
	8016: Prefix + "FindInterestingEntitiesByEntityID",
	8017: Prefix + "FindInterestingEntitiesByRecordID",
	8018: Prefix + "FindNetworkByEntityID",
	8019: Prefix + "FindNetworkByEntityID_V2",
	8020: Prefix + "FindNetworkByRecordID",
	8021: Prefix + "FindNetworkByRecordID_V2",
	8022: Prefix + "FindPathByEntityID",
	8023: Prefix + "FindPathByEntityID_V2",
	8024: Prefix + "FindPathByRecordID",
	8025: Prefix + "FindPathByRecordID_V2",
	8026: Prefix + "FindPathExcludingByEntityID",
	8027: Prefix + "FindPathExcludingByEntityID_V2",
	8028: Prefix + "FindPathExcludingByRecordID",
	8029: Prefix + "FindPathExcludingByRecordID_V2",
	8030: Prefix + "FindPathIncludingSourceByEntityID",
	8031: Prefix + "FindPathIncludingSourceByEntityID_V2",
	8032: Prefix + "FindPathIncludingSourceByRecordID",
	8033: Prefix + "FindPathIncludingSourceByRecordID_V2",
	8034: Prefix + "GetActiveConfigID",
	8035: Prefix + "GetEntityByEntityID",
	8036: Prefix + "GetEntityByEntityID_V2",
	8037: Prefix + "GetEntityByRecordID",
	8038: Prefix + "GetEntityByRecordID_V2",
	8039: Prefix + "GetRecord",
	8040: Prefix + "GetRecord_V2",
	8041: Prefix + "GetRedoRecord",
	8042: Prefix + "GetRepositoryLastModifiedTime",
	8043: Prefix + "GetVirtualEntityByRecordID",
	8044: Prefix + "GetVirtualEntityByRecordID_V2",
	8045: Prefix + "HowEntityByEntityID",
	8046: Prefix + "HowEntityByEntityID_V2",
	8047: Prefix + "Init",
	8048: Prefix + "InitWithConfigID",
	8049: Prefix + "PrimeEngine",
	8050: Prefix + "Process",
	8051: Prefix + "ProcessRedoRecord",
	8052: Prefix + "ProcessRedoRecordWithInfo",
	8056: Prefix + "PurgeRepository",
	8057: Prefix + "ReevaluateEntity",
	8058: Prefix + "ReevaluateEntityWithInfo",
	8059: Prefix + "ReevaluateRecord",
	8060: Prefix + "ReevaluateRecordWithInfo",
	8061: Prefix + "Reinit",
	8062: Prefix + "ReplaceRecord",
	8063: Prefix + "ReplaceRecordWithInfo",
	8064: Prefix + "SearchByAttributes",
	8065: Prefix + "SearchByAttributes_V2",
	8066: Prefix + "Stats",
	8067: Prefix + "WhyEntities",
	8068: Prefix + "WhyEntities_V2",
	8073: Prefix + "WhyRecords",
	8074: Prefix + "WhyRecords_V2",
	8075: Prefix + "GetSdkId",
	8076: Prefix + "RegisterObserver",
	8077: Prefix + "SetLogLevel",
	8078: Prefix + "UnregisterObserver",
	8079: Prefix + "ExportCSVEntityReport",
	8080: Prefix + "ExportJSONEntityReport",
}

// Status strings for specific g2engine messages.
var IdStatuses = map[int]string{}
