name: Go test darwin

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  sdk-versions:
    runs-on: ubuntu-latest
    outputs:
      senzingsdk-versions: ${{ steps.cfg.outputs.senzingsdk-versions }}
    steps:
      - id: cfg
        uses: senzing-factory/build-resources/sdk-versions@v4

  go-test-darwin:
    name: "Go test with Senzing: ${{ matrix.senzingsdk-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    needs: sdk-versions
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: ["1.26"]
        os: [macos-latest]
        senzingsdk-version: ${{ fromJSON(needs.sdk-versions.outputs.senzingsdk-versions) }}
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go test
        env:
          SENZING_SDK_VERSION: ${{ matrix.senzingsdk-version }}
        run: |
          go test -json -v -p 1 -coverprofile=./cover-${SENZING_SDK_VERSION}.out -covermode=atomic -coverpkg=./... ./...  2>&1 | tee "/tmp/gotest-${SENZING_SDK_VERSION}.log" | gotestfmt

      - name: Store coverage file
        uses: actions/upload-artifact@v6
        with:
          name: "cover-${{ matrix.senzingsdk-version }}.out"
          path: "./cover-${{ matrix.senzingsdk-version }}.out"

      - name: Upload test log
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: "test-log-${{ matrix.senzingsdk-version }}"
          path: "/tmp/gotest-${{ matrix.senzingsdk-version }}.log"
          if-no-files-found: error

  coverage:
    name: Coverage
    needs: go-test-darwin
    permissions:
      contents: read
    uses: senzing-factory/build-resources/.github/workflows/go-coverage.yaml@v4
    with:
      coverage-config: ./.github/coverage/testcoverage.yaml
      profile: "cover-production-v4.out,cover-staging-v4.out"
